# Generated by Django 5.1.7 on 2025-03-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплата')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
                ('telegram_id', models.CharField(max_length=50, verbose_name='Телеграм-айди пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
